package a;


import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author prathamesh
 */
public class Clothes extends javax.swing.JFrame {

    /**
     * Creates new form Electronics
     */
    public Clothes() {
        initComponents();
                        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jL_Asus25 = new javax.swing.JLabel();
        jL_Asus26 = new javax.swing.JLabel();
        jL_Asus27 = new javax.swing.JLabel();
        jL_Asus28 = new javax.swing.JLabel();
        jL_Asus29 = new javax.swing.JLabel();
        jL_Asus30 = new javax.swing.JLabel();
        jL_Asus31 = new javax.swing.JLabel();
        jL_Asus32 = new javax.swing.JLabel();
        jL_Asus33 = new javax.swing.JLabel();
        jL_Asus34 = new javax.swing.JLabel();
        jL_Asus35 = new javax.swing.JLabel();
        jL_Asus36 = new javax.swing.JLabel();
        jL_Asus37 = new javax.swing.JLabel();
        jL_Asus38 = new javax.swing.JLabel();
        jL_Asus39 = new javax.swing.JLabel();
        jL_Asus40 = new javax.swing.JLabel();
        jL_Asus41 = new javax.swing.JLabel();
        jL_Asus42 = new javax.swing.JLabel();
        jL_Asus43 = new javax.swing.JLabel();
        jL_Asus44 = new javax.swing.JLabel();
        jL_Asus45 = new javax.swing.JLabel();
        jL_Asus46 = new javax.swing.JLabel();
        jL_Asus47 = new javax.swing.JLabel();
        jL_Asus48 = new javax.swing.JLabel();
        jL_Asus49 = new javax.swing.JLabel();
        jL_Asus50 = new javax.swing.JLabel();
        jL_Asus51 = new javax.swing.JLabel();
        jL_Asus52 = new javax.swing.JLabel();
        jL_Asus53 = new javax.swing.JLabel();
        jL_Asus54 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jL_Close1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jL_Minimizze1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\prathamesh\\Documents\\NetBeansProjects\\LoginAndReg\\images\\Cothes\\shirt.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\prathamesh\\Documents\\NetBeansProjects\\LoginAndReg\\images\\Cothes\\baby.jpg")); // NOI18N
        jLabel2.setText("jLabel1");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\prathamesh\\Documents\\NetBeansProjects\\LoginAndReg\\images\\Cothes\\Black_hoodie.jpg")); // NOI18N
        jLabel4.setText("jLabel1");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\prathamesh\\Documents\\NetBeansProjects\\LoginAndReg\\images\\Cothes\\frock.jpg")); // NOI18N
        jLabel6.setText("jLabel1");

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\prathamesh\\Documents\\NetBeansProjects\\LoginAndReg\\images\\Cothes\\girldress.jpg")); // NOI18N
        jLabel7.setText("jLabel1");

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\prathamesh\\Documents\\NetBeansProjects\\LoginAndReg\\images\\Cothes\\jeans.jpg")); // NOI18N
        jLabel10.setText("jLabel1");

        jButton7.setBackground(new java.awt.Color(0, 153, 0));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Buy Now");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 153, 0));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Buy Now");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 153, 0));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("Buy Now");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(0, 153, 0));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setText("Buy Now");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(0, 153, 0));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setText("Buy Now");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(0, 153, 0));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setText("Buy Now");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jL_Asus25.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus25.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus25.setText("BabySkool Pair");
        jL_Asus25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus25MouseClicked(evt);
            }
        });

        jL_Asus26.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus26.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus26.setText("Age group:2-3 yrs");
        jL_Asus26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus26MouseClicked(evt);
            }
        });

        jL_Asus27.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus27.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus27.setText("    Fabric: Cotton ,Jeans");
        jL_Asus27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus27MouseClicked(evt);
            }
        });

        jL_Asus28.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus28.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus28.setText("900");
        jL_Asus28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus28MouseClicked(evt);
            }
        });

        jL_Asus29.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus29.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus29.setText("750");
        jL_Asus29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus29MouseClicked(evt);
            }
        });

        jL_Asus30.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus30.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus30.setText("1050");
        jL_Asus30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus30MouseClicked(evt);
            }
        });

        jL_Asus31.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus31.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus31.setText("800");
        jL_Asus31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus31MouseClicked(evt);
            }
        });

        jL_Asus32.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus32.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus32.setText("    Full Sleeve ");
        jL_Asus32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus32MouseClicked(evt);
            }
        });

        jL_Asus33.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus33.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus33.setText("1200");
        jL_Asus33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus33MouseClicked(evt);
            }
        });

        jL_Asus34.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus34.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus34.setText("    Fabric: COTTON ");
        jL_Asus34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus34MouseClicked(evt);
            }
        });

        jL_Asus35.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus35.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus35.setText("    Pattern: Printed ");
        jL_Asus35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus35MouseClicked(evt);
            }
        });

        jL_Asus36.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus36.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus36.setText("    Pattern: Floral");
        jL_Asus36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus36MouseClicked(evt);
            }
        });

        jL_Asus37.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus37.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus37.setText("    Mid Rise Jeans ");
        jL_Asus37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus37MouseClicked(evt);
            }
        });

        jL_Asus38.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus38.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus38.setText("    Fabric: Polyester Linen Blend ");
        jL_Asus38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus38MouseClicked(evt);
            }
        });

        jL_Asus39.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus39.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus39.setText("Size:Large");
        jL_Asus39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus39MouseClicked(evt);
            }
        });

        jL_Asus40.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus40.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus40.setText("    Fit: Regular ");
        jL_Asus40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus40MouseClicked(evt);
            }
        });

        jL_Asus41.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus41.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus41.setText("Occasion      Casual ");
        jL_Asus41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus41MouseClicked(evt);
            }
        });

        jL_Asus42.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus42.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus42.setText("Ben Martin Regular Men's Dark Blue Jeans");
        jL_Asus42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus42MouseClicked(evt);
            }
        });

        jL_Asus43.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus43.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus43.setText("Sleeve :Full Sleeve , Hooded :Yes ");
        jL_Asus43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus43MouseClicked(evt);
            }
        });

        jL_Asus44.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus44.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus44.setText("Reversible:No    Knit Type:Fleece ");
        jL_Asus44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus44MouseClicked(evt);
            }
        });

        jL_Asus45.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus45.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus45.setText("Occasion      Casual ");
        jL_Asus45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus45MouseClicked(evt);
            }
        });

        jL_Asus46.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus46.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus46.setText("    Fabric: Cotton ");
        jL_Asus46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus46MouseClicked(evt);
            }
        });

        jL_Asus47.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus47.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus47.setText("    Midi/Knee Length Dress ");
        jL_Asus47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus47MouseClicked(evt);
            }
        });

        jL_Asus48.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus48.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus48.setText("    Color: Multicolor ");
        jL_Asus48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus48MouseClicked(evt);
            }
        });

        jL_Asus49.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus49.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus49.setText("Fabric:Silk");
        jL_Asus49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus49MouseClicked(evt);
            }
        });

        jL_Asus50.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus50.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus50.setText("Alan Jones Full Sleeve Solid Men's Sweatshirt");
        jL_Asus50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus50MouseClicked(evt);
            }
        });

        jL_Asus51.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus51.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus51.setText("Bella Moda Girls Midi/Knee Length Casual Dress");
        jL_Asus51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus51MouseClicked(evt);
            }
        });

        jL_Asus52.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus52.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus52.setText("Gown");
        jL_Asus52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus52MouseClicked(evt);
            }
        });

        jL_Asus53.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus53.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus53.setText(".Adidas Printed Men's Round Neck Black T-Shirt ");
        jL_Asus53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus53MouseClicked(evt);
            }
        });

        jL_Asus54.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus54.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus54.setText("6800");
        jL_Asus54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus54MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jL_Close1.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jL_Close1.setForeground(new java.awt.Color(255, 255, 255));
        jL_Close1.setText("X");
        jL_Close1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_Close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Close1MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Sitka Heading", 1, 38)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("KART");

        jL_Minimizze1.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jL_Minimizze1.setForeground(new java.awt.Color(255, 255, 255));
        jL_Minimizze1.setText("-");
        jL_Minimizze1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_Minimizze1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Minimizze1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL_Minimizze1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jL_Close1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Close1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Minimizze1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jL_Asus25, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jL_Asus33, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(322, 322, 322)
                        .addComponent(jL_Asus50, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jL_Asus30, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_Asus45, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_Asus26, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_Asus27, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(344, 344, 344)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jL_Asus41, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_Asus43, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(jL_Asus44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(676, 676, 676)
                        .addComponent(jButton8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jL_Asus51, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jL_Asus31, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(277, 277, 277)
                        .addComponent(jL_Asus52, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jL_Asus54, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_Asus46, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_Asus47, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_Asus48, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(309, 309, 309)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_Asus49, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_Asus39, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_Asus36, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(692, 692, 692)
                        .addComponent(jButton10))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_Asus42)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jL_Asus40, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jL_Asus34, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jL_Asus37, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(11, 11, 11)
                        .addComponent(jL_Asus28, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(290, 290, 290)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jL_Asus38)
                                    .addComponent(jL_Asus35, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jL_Asus32, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jL_Asus53, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL_Asus29, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton11)
                        .addGap(534, 534, 534)
                        .addComponent(jButton12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_Asus25, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Asus33, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Asus50, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jL_Asus30, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jButton7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jL_Asus45, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jL_Asus26, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jL_Asus27, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jL_Asus41, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jL_Asus43, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jL_Asus44, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(jButton8)
                .addGap(65, 65, 65)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_Asus51, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Asus31, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jL_Asus52, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jL_Asus54, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jButton9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jL_Asus46, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jL_Asus47, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jL_Asus48, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jL_Asus49, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jL_Asus39, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jL_Asus36, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(jButton10)
                .addGap(74, 74, 74)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jL_Asus42, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jL_Asus40, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jL_Asus34, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jL_Asus37, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jL_Asus28, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL_Asus53, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_Asus29, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jL_Asus38, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jL_Asus35, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jL_Asus32, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11)
                    .addComponent(jButton12))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jL_Minimizze1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Minimizze1MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jL_Minimizze1MouseClicked

    private void jL_Close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Close1MouseClicked
        this.dispose();
        AfterLogin al=new AfterLogin();
        al.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Close1MouseClicked

    private void jL_Asus54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus54MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus54MouseClicked

    private void jL_Asus53MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus53MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus53MouseClicked

    private void jL_Asus52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus52MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus52MouseClicked

    private void jL_Asus51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus51MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus51MouseClicked

    private void jL_Asus50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus50MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus50MouseClicked

    private void jL_Asus49MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus49MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus49MouseClicked

    private void jL_Asus48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus48MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus48MouseClicked

    private void jL_Asus47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus47MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus47MouseClicked

    private void jL_Asus46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus46MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus46MouseClicked

    private void jL_Asus45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus45MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus45MouseClicked

    private void jL_Asus44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus44MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus44MouseClicked

    private void jL_Asus43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus43MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus43MouseClicked

    private void jL_Asus42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus42MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus42MouseClicked

    private void jL_Asus41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus41MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus41MouseClicked

    private void jL_Asus40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus40MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus40MouseClicked

    private void jL_Asus39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus39MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus39MouseClicked

    private void jL_Asus38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus38MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus38MouseClicked

    private void jL_Asus37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus37MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus37MouseClicked

    private void jL_Asus36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus36MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus36MouseClicked

    private void jL_Asus35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus35MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus35MouseClicked

    private void jL_Asus34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus34MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus34MouseClicked

    private void jL_Asus33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus33MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus33MouseClicked

    private void jL_Asus32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus32MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus32MouseClicked

    private void jL_Asus31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus31MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus31MouseClicked

    private void jL_Asus30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus30MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus30MouseClicked

    private void jL_Asus29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus29MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus29MouseClicked

    private void jL_Asus28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus28MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus28MouseClicked

    private void jL_Asus27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus27MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus27MouseClicked

    private void jL_Asus26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus26MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus26MouseClicked

    private void jL_Asus25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus25MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus25MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Electronics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Electronics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Electronics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Electronics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Electronics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jL_Asus25;
    private javax.swing.JLabel jL_Asus26;
    private javax.swing.JLabel jL_Asus27;
    private javax.swing.JLabel jL_Asus28;
    private javax.swing.JLabel jL_Asus29;
    private javax.swing.JLabel jL_Asus30;
    private javax.swing.JLabel jL_Asus31;
    private javax.swing.JLabel jL_Asus32;
    private javax.swing.JLabel jL_Asus33;
    private javax.swing.JLabel jL_Asus34;
    private javax.swing.JLabel jL_Asus35;
    private javax.swing.JLabel jL_Asus36;
    private javax.swing.JLabel jL_Asus37;
    private javax.swing.JLabel jL_Asus38;
    private javax.swing.JLabel jL_Asus39;
    private javax.swing.JLabel jL_Asus40;
    private javax.swing.JLabel jL_Asus41;
    private javax.swing.JLabel jL_Asus42;
    private javax.swing.JLabel jL_Asus43;
    private javax.swing.JLabel jL_Asus44;
    private javax.swing.JLabel jL_Asus45;
    private javax.swing.JLabel jL_Asus46;
    private javax.swing.JLabel jL_Asus47;
    private javax.swing.JLabel jL_Asus48;
    private javax.swing.JLabel jL_Asus49;
    private javax.swing.JLabel jL_Asus50;
    private javax.swing.JLabel jL_Asus51;
    private javax.swing.JLabel jL_Asus52;
    private javax.swing.JLabel jL_Asus53;
    private javax.swing.JLabel jL_Asus54;
    private javax.swing.JLabel jL_Close1;
    private javax.swing.JLabel jL_Minimizze1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
