package a;


import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author prathamesh
 */
public class Furniture extends javax.swing.JFrame {

    /**
     * Creates new form Electronics
     */
    public Furniture() {
        initComponents();
                        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jL_Close1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jL_Minimizze1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jL_Asus = new javax.swing.JLabel();
        jL_Asus1 = new javax.swing.JLabel();
        jL_Asus2 = new javax.swing.JLabel();
        jL_Asus3 = new javax.swing.JLabel();
        jL_Asus4 = new javax.swing.JLabel();
        jL_Asus5 = new javax.swing.JLabel();
        jL_Asus6 = new javax.swing.JLabel();
        jL_Asus7 = new javax.swing.JLabel();
        jL_Asus8 = new javax.swing.JLabel();
        jL_Asus9 = new javax.swing.JLabel();
        jL_Asus10 = new javax.swing.JLabel();
        jL_Asus11 = new javax.swing.JLabel();
        jL_Asus12 = new javax.swing.JLabel();
        jL_Asus13 = new javax.swing.JLabel();
        jL_Asus14 = new javax.swing.JLabel();
        jL_Asus15 = new javax.swing.JLabel();
        jL_Asus16 = new javax.swing.JLabel();
        jL_Asus17 = new javax.swing.JLabel();
        jL_Asus18 = new javax.swing.JLabel();
        jL_Asus19 = new javax.swing.JLabel();
        jL_Asus20 = new javax.swing.JLabel();
        jL_Asus21 = new javax.swing.JLabel();
        jL_Asus22 = new javax.swing.JLabel();
        jL_Asus23 = new javax.swing.JLabel();
        jL_Asus24 = new javax.swing.JLabel();
        jL_Asus25 = new javax.swing.JLabel();
        jL_Asus26 = new javax.swing.JLabel();
        jL_Asus27 = new javax.swing.JLabel();
        jL_Asus28 = new javax.swing.JLabel();
        jL_Asus29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jL_Close1.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jL_Close1.setForeground(new java.awt.Color(255, 255, 255));
        jL_Close1.setText("X");
        jL_Close1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_Close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Close1MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Sitka Heading", 1, 38)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("KART");

        jL_Minimizze1.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jL_Minimizze1.setForeground(new java.awt.Color(255, 255, 255));
        jL_Minimizze1.setText("-");
        jL_Minimizze1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_Minimizze1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Minimizze1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL_Minimizze1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jL_Close1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Close1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Minimizze1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\prathamesh\\Documents\\NetBeansProjects\\LoginAndReg\\images\\furniture\\chair.jpg")); // NOI18N
        jLabel1.setText("IMAGE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\prathamesh\\Documents\\NetBeansProjects\\LoginAndReg\\images\\furniture\\sofa.jpeg")); // NOI18N
        jLabel2.setText("IMAGE");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\prathamesh\\Documents\\NetBeansProjects\\LoginAndReg\\images\\furniture\\table.jpg")); // NOI18N
        jLabel3.setText("IMAGE");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\prathamesh\\Documents\\NetBeansProjects\\LoginAndReg\\images\\furniture\\cupboard.jpg")); // NOI18N
        jLabel4.setText("IMAGE");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\prathamesh\\Documents\\NetBeansProjects\\LoginAndReg\\images\\furniture\\bed.jpg")); // NOI18N
        jLabel6.setText("IMAGE");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\prathamesh\\Documents\\NetBeansProjects\\LoginAndReg\\images\\furniture\\dining.jpg")); // NOI18N
        jLabel7.setText("IMAGE");

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Buy Now");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Buy Now");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 153, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Buy Now");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 153, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Buy Now");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 153, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Buy Now");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 153, 0));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Buy Now");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jL_Asus.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus.setText("W x H x D: 156.50 cm x 88 cm x 221 cm ");
        jL_Asus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_AsusMouseClicked(evt);
            }
        });

        jL_Asus1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus1.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus1.setText("Delivery Condition: Knock Down ");
        jL_Asus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus1MouseClicked(evt);
            }
        });

        jL_Asus2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus2.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus2.setText("    Ethnic & Traditional Style ");
        jL_Asus2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus2MouseClicked(evt);
            }
        });

        jL_Asus3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus3.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus3.setText("Material Subtype: Particle Board ");
        jL_Asus3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus3MouseClicked(evt);
            }
        });

        jL_Asus4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus4.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus4.setText("Spacewood Mayflower Engineered Wood Queen Bed ");
        jL_Asus4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus4MouseClicked(evt);
            }
        });

        jL_Asus5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus5.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus5.setText("Kurlon Dazzle Fabric 2 Seater Sofa");
        jL_Asus5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus5MouseClicked(evt);
            }
        });

        jL_Asus6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus6.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus6.setText("HOME PUFF Solid Wood Portable  Table");
        jL_Asus6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus6MouseClicked(evt);
            }
        });

        jL_Asus7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus7.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus7.setText("The Attic Solid Wood Cupboard  ");
        jL_Asus7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus7MouseClicked(evt);
            }
        });

        jL_Asus8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus8.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus8.setText("Woodness Glass 6 Seater Dining Set  ");
        jL_Asus8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus8MouseClicked(evt);
            }
        });

        jL_Asus9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus9.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus9.setText("HOF Kenzo 551 Premium Leatherette Office Arm Chair");
        jL_Asus9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus9MouseClicked(evt);
            }
        });

        jL_Asus10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus10.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus10.setText("Upholstery Included ");
        jL_Asus10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus10MouseClicked(evt);
            }
        });

        jL_Asus11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus11.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus11.setText("W x H x D: 37.5 cm x 96 cm x 44 cm ");
        jL_Asus11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus11MouseClicked(evt);
            }
        });

        jL_Asus12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus12.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus12.setText("    Pre-assembled ");
        jL_Asus12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus12MouseClicked(evt);
            }
        });

        jL_Asus13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus13.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus13.setText("able Top Material: Hardwood");
        jL_Asus13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus13MouseClicked(evt);
            }
        });

        jL_Asus14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus14.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus14.setText("    W x H x D: 60 x 80 x 35 cm ");
        jL_Asus14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus14MouseClicked(evt);
            }
        });

        jL_Asus15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus15.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus15.setText("    Upholstery Type: Tufted ");
        jL_Asus15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus15MouseClicked(evt);
            }
        });

        jL_Asus16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus16.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus16.setText("Foldable : No    Adjustable Height : No");
        jL_Asus16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus16MouseClicked(evt);
            }
        });

        jL_Asus17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus17.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus17.setText("    W x H: 66 cm x 102 cm ");
        jL_Asus17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus17MouseClicked(evt);
            }
        });

        jL_Asus18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus18.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus18.setText("Primary Material         Solid Wood");
        jL_Asus18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus18MouseClicked(evt);
            }
        });

        jL_Asus19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus19.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus19.setText("    Suitable For Study & Home Office ");
        jL_Asus19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus19MouseClicked(evt);
            }
        });

        jL_Asus20.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus20.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus20.setText("    Upholstery Included ");
        jL_Asus20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus20MouseClicked(evt);
            }
        });

        jL_Asus21.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus21.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus21.setText("    Filling Material: Foam ");
        jL_Asus21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus21MouseClicked(evt);
            }
        });

        jL_Asus22.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus22.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus22.setText("Finish Color - Grey");
        jL_Asus22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus22MouseClicked(evt);
            }
        });

        jL_Asus23.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus23.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus23.setText("    Delivery Condition: DIY(Do-It-Yourself) ");
        jL_Asus23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus23MouseClicked(evt);
            }
        });

        jL_Asus24.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus24.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus24.setText("26000");
        jL_Asus24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus24MouseClicked(evt);
            }
        });

        jL_Asus25.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus25.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus25.setText("4200");
        jL_Asus25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus25MouseClicked(evt);
            }
        });

        jL_Asus26.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus26.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus26.setText("6500");
        jL_Asus26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus26MouseClicked(evt);
            }
        });

        jL_Asus27.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus27.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus27.setText("1800");
        jL_Asus27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus27MouseClicked(evt);
            }
        });

        jL_Asus28.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus28.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus28.setText("8000");
        jL_Asus28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus28MouseClicked(evt);
            }
        });

        jL_Asus29.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jL_Asus29.setForeground(new java.awt.Color(204, 204, 204));
        jL_Asus29.setText("18500");
        jL_Asus29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Asus29MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jL_Asus16)
                                    .addComponent(jL_Asus18, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jL_Asus19, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(jButton2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jL_Asus17)
                                    .addComponent(jL_Asus15)
                                    .addComponent(jL_Asus23)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jL_Asus6)
                                .addGap(58, 58, 58)
                                .addComponent(jL_Asus27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton5)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jL_Asus9)
                                .addGap(40, 40, 40)
                                .addComponent(jL_Asus25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jL_Asus8)
                                .addGap(65, 65, 65)
                                .addComponent(jL_Asus29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jL_Asus10)
                                    .addComponent(jL_Asus13)
                                    .addComponent(jL_Asus11)))
                            .addComponent(jButton4))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jL_Asus7)
                        .addGap(30, 30, 30)
                        .addComponent(jL_Asus28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jL_Asus5)
                                .addGap(37, 37, 37)
                                .addComponent(jL_Asus26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jL_Asus22))
                                    .addComponent(jL_Asus20)
                                    .addComponent(jL_Asus21)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jL_Asus)
                                    .addComponent(jL_Asus3)
                                    .addComponent(jL_Asus1)))
                            .addComponent(jButton3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jL_Asus2))
                                    .addComponent(jL_Asus12)
                                    .addComponent(jL_Asus14)))
                            .addComponent(jButton6)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jL_Asus4)
                                .addGap(41, 41, 41)
                                .addComponent(jL_Asus24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton7))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Asus7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Asus9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Asus28, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Asus25, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jL_Asus17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL_Asus15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL_Asus23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jL_Asus2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL_Asus14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL_Asus12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL_Asus5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_Asus26, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jL_Asus21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL_Asus20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL_Asus22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jL_Asus8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL_Asus29, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addComponent(jL_Asus13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL_Asus10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jL_Asus11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButton6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL_Asus4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_Asus24, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jL_Asus3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jL_Asus, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL_Asus1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jL_Asus16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addGap(65, 65, 65))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL_Asus6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_Asus27, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jL_Asus18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL_Asus19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(70, 70, 70))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jL_Close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Close1MouseClicked
        this.dispose();
        AfterLogin al=new AfterLogin();
        al.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Close1MouseClicked

    private void jL_Minimizze1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Minimizze1MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jL_Minimizze1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jL_AsusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_AsusMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_AsusMouseClicked

    private void jL_Asus1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus1MouseClicked

    private void jL_Asus2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus2MouseClicked

    private void jL_Asus3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus3MouseClicked

    private void jL_Asus4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus4MouseClicked

    private void jL_Asus5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus5MouseClicked

    private void jL_Asus6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus6MouseClicked

    private void jL_Asus7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus7MouseClicked

    private void jL_Asus8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus8MouseClicked

    private void jL_Asus9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus9MouseClicked

    private void jL_Asus10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus10MouseClicked

    private void jL_Asus11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus11MouseClicked

    private void jL_Asus12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus12MouseClicked

    private void jL_Asus13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus13MouseClicked

    private void jL_Asus14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus14MouseClicked

    private void jL_Asus15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus15MouseClicked

    private void jL_Asus16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus16MouseClicked

    private void jL_Asus17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus17MouseClicked

    private void jL_Asus18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus18MouseClicked

    private void jL_Asus19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus19MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus19MouseClicked

    private void jL_Asus20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus20MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus20MouseClicked

    private void jL_Asus21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus21MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus21MouseClicked

    private void jL_Asus22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus22MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus22MouseClicked

    private void jL_Asus23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus23MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus23MouseClicked

    private void jL_Asus24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus24MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus24MouseClicked

    private void jL_Asus25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus25MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus25MouseClicked

    private void jL_Asus26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus26MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus26MouseClicked

    private void jL_Asus27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus27MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus27MouseClicked

    private void jL_Asus28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus28MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus28MouseClicked

    private void jL_Asus29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Asus29MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_Asus29MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Electronics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Electronics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Electronics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Electronics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Electronics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jL_Asus;
    private javax.swing.JLabel jL_Asus1;
    private javax.swing.JLabel jL_Asus10;
    private javax.swing.JLabel jL_Asus11;
    private javax.swing.JLabel jL_Asus12;
    private javax.swing.JLabel jL_Asus13;
    private javax.swing.JLabel jL_Asus14;
    private javax.swing.JLabel jL_Asus15;
    private javax.swing.JLabel jL_Asus16;
    private javax.swing.JLabel jL_Asus17;
    private javax.swing.JLabel jL_Asus18;
    private javax.swing.JLabel jL_Asus19;
    private javax.swing.JLabel jL_Asus2;
    private javax.swing.JLabel jL_Asus20;
    private javax.swing.JLabel jL_Asus21;
    private javax.swing.JLabel jL_Asus22;
    private javax.swing.JLabel jL_Asus23;
    private javax.swing.JLabel jL_Asus24;
    private javax.swing.JLabel jL_Asus25;
    private javax.swing.JLabel jL_Asus26;
    private javax.swing.JLabel jL_Asus27;
    private javax.swing.JLabel jL_Asus28;
    private javax.swing.JLabel jL_Asus29;
    private javax.swing.JLabel jL_Asus3;
    private javax.swing.JLabel jL_Asus4;
    private javax.swing.JLabel jL_Asus5;
    private javax.swing.JLabel jL_Asus6;
    private javax.swing.JLabel jL_Asus7;
    private javax.swing.JLabel jL_Asus8;
    private javax.swing.JLabel jL_Asus9;
    private javax.swing.JLabel jL_Close1;
    private javax.swing.JLabel jL_Minimizze1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
