package a;


import com.mongodb.*;
import com.mongodb.MongoClient;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author prathamesh
 */
public class LoginForm extends javax.swing.JFrame {
    /**
     * 
     * Creates new form LoginForm
     */
    public static String pass_uname;
        public   static String n;

    
    
    public LoginForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jL_Close = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jL_Minimizze = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TF_Username = new javax.swing.JTextField();
        TF_Password = new javax.swing.JPasswordField();
        jB_Login = new javax.swing.JButton();
        jB_Cancel = new javax.swing.JButton();
        jB_NewAccount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jL_Close.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jL_Close.setForeground(new java.awt.Color(255, 255, 255));
        jL_Close.setText("X");
        jL_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_CloseMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Sitka Heading", 1, 38)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Login Form");

        jL_Minimizze.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jL_Minimizze.setForeground(new java.awt.Color(255, 255, 255));
        jL_Minimizze.setText("-");
        jL_Minimizze.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_Minimizze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_MinimizzeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL_Minimizze)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jL_Close)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Minimizze, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Password:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Username:");

        TF_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_UsernameActionPerformed(evt);
            }
        });

        jB_Login.setBackground(new java.awt.Color(0, 153, 255));
        jB_Login.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jB_Login.setText("Login");
        jB_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_LoginMouseClicked(evt);
            }
        });
        jB_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_LoginActionPerformed(evt);
            }
        });

        jB_Cancel.setBackground(new java.awt.Color(255, 0, 51));
        jB_Cancel.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jB_Cancel.setText("Cancel");
        jB_Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jB_CancelMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_CancelMouseClicked(evt);
            }
        });
        jB_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_CancelActionPerformed(evt);
            }
        });

        jB_NewAccount.setBackground(new java.awt.Color(102, 204, 0));
        jB_NewAccount.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jB_NewAccount.setText("Create new account");
        jB_NewAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_NewAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_NewAccountMouseClicked(evt);
            }
        });
        jB_NewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_NewAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TF_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF_Password)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jB_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jB_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jB_NewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_Username))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_Password))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Login)
                    .addComponent(jB_Cancel))
                .addGap(28, 28, 28)
                .addComponent(jB_NewAccount)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_UsernameActionPerformed

    private void jL_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_CloseMouseClicked

        System.exit(0);
    }//GEN-LAST:event_jL_CloseMouseClicked

    private void jL_MinimizzeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_MinimizzeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jL_MinimizzeMouseClicked

    private void jB_NewAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_NewAccountMouseClicked

        RegisterForm reg = new RegisterForm();
        reg.setVisible(true);      //show the registration form
        reg.pack();
        reg.setLocationRelativeTo(null);      //in middle of screen
        reg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);         //??
        this.dispose();                         //to close login form after new acc button clicked

    }//GEN-LAST:event_jB_NewAccountMouseClicked

    private void jB_NewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_NewAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_NewAccountActionPerformed

    private void jB_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_CancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_CancelActionPerformed

    private void jB_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_LoginActionPerformed

    private void jB_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_LoginMouseClicked
        // TODO add your handling code here:
      
        
        MongoClient mc/*Client Name*/=new MongoClient("localhost",27017);
        
        DB info/*Database Name*/=mc.getDB("info");                  //Create/Use Database
        DBCollection register=info.getCollection("register");                 //Create Collection
        BasicDBObject bdo =new BasicDBObject("UName",TF_Username.getText()).append("Password",TF_Password.getText());
       
        DBCursor dbc = register.find(bdo);
        
        if(TF_Username.getText().toString().equals("")||TF_Password.getText().toString().equals(""))    
        {
            JOptionPane.showMessageDialog(null,"Enter Your Username And Password To Login");
        }
        
        else
        {
        if(dbc.hasNext())
        {
            String pass_uname=TF_Username.getText();
            AfterLogin af = new AfterLogin(pass_uname);
            af.setVisible(true);
            af.pack();
            af.setLocationRelativeTo(null);
            af.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }//Insert into DB
        else
        {
            JOptionPane.showMessageDialog(null,"Entered Username Or Password Does Not Match");
        }
    }//GEN-LAST:event_jB_LoginMouseClicked
}
    
    private void jB_CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_CancelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_CancelMouseEntered

    private void jB_CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_CancelMouseClicked
Home h=new Home();
h.setVisible(true);
h.pack();
h.setLocationRelativeTo(null);
h.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
this.dispose();     }//GEN-LAST:event_jB_CancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField TF_Password;
    private javax.swing.JTextField TF_Username;
    private javax.swing.JButton jB_Cancel;
    private javax.swing.JButton jB_Login;
    private javax.swing.JButton jB_NewAccount;
    private javax.swing.JLabel jL_Close;
    private javax.swing.JLabel jL_Minimizze;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
